# Generated by Django 5.1.4 on 2024-12-23 19:41

from django.db import migrations, models

def create_default_fruits(apps, schema_editor):
    Fruits = apps.get_model('viewComponents', 'Fruits')
    Fruits.objects.create(name='Apple', color='Red', price=1.0, quantity=100)
    Fruits.objects.create(name='Banana', color='Yellow', price=0.5, quantity=150)
    Fruits.objects.create(name='Orange', color='Orange', price=0.8, quantity=120)
    Fruits.objects.create(name='Grapes', color='Green', price=2.0, quantity=80)
    Fruits.objects.create(name='Mango', color='Golden', price=1.5, quantity=60)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(create_default_fruits),
    ]
